db:
version: '3.8'
services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: rateio_db
    ports:
      - "5432:5432" # Mapeia a porta do container para a porta local
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

